-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: vendor/mwstake/mediawiki-component-processmanager/db/patch_process_claim.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/processes
  ADD COLUMN p_claimed_by BLOB DEFAULT NULL;
