-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db/patch_additional_args.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/processes
ADD  p_additional_script_args LONGTEXT DEFAULT NULL;