-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/process_plugin_lock.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE process_plugin_lock (
  ppl_plugin_name TEXT NOT NULL,
  ppl_locked_at TEXT NOT NULL,
  ppl_claimed_by TEXT NOT NULL,
  PRIMARY KEY(ppl_plugin_name)
);
