-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/processes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE processes (
  p_pid TEXT NOT NULL, p_state TEXT NOT NULL,
  p_exitcode SMALLINT DEFAULT NULL,
  p_exitstatus TEXT DEFAULT '', p_started TIMESTAMPTZ DEFAULT NULL,
  p_timeout INT NOT NULL, p_output TEXT DEFAULT NULL,
  p_steps TEXT DEFAULT NULL, p_last_completed_step TEXT DEFAULT NULL
);
